function trial_folder_path = BuildTrialFolderPath(date, cell_name, trial_name)
trial_folder_path = fullfile('D:\data\patching\', ...
                                date, ...
                                cell_name, ...
                                trial_name);
                            
end