    function cell_params = ReadCellParamsFromFile(file_path)
        str = fileread(file_path);
        val_indices = strsplit(str, '<Val>');
        val_indices = val_indices(2:end);

        cell_params = []; 
        for ii = 1 : numel(val_indices)
            value = str2num(strtok(val_indices{ii}, '</Val>'));
            cell_params(ii) = value; 
        end

        cell_params = struct(...
            'Ihold', cell_params(1), ...
            'Rm', cell_params(2), ...
            'Ra', cell_params(3), ...
            'Cm', cell_params(4), ...
            'tau', cell_params(5), ...
            'Rt', cell_params(6) ...
        );
    end